# Generated by Django 4.0.2 on 2022-02-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_world_primiere'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={},
        ),
    ]
